export { apiClient, API_BASE_URL } from '@/config/api-client.config';
export * from './tokenStorage';
export * from './authApi';
export * from './usersApi';
export * from './walletApi';
export * from './membershipApi';
export * from './paymentsApi';
export * from './apiKeysApi';
export * from './referralsApi';
export * from './reviewsApi';
export * from './ticketsApi';
export * from './notificationsApi';

// adminApi re-declares types from paymentsApi/membershipApi, so exclude duplicates
export {
  // Admin User types & functions
  type AdminUser,
  type AdminUserDetail,
  type UserStatistics,
  type AdminUsersResponse,
  type AdminUserQueryParams,
  type AdminUpdateUserRequest,
  type ChangeRoleRequest,
  type SetLimitsRequest,
  type SetAbuseScoreRequest,
  type BanUserRequest,
  type SuspendUserRequest,
  getAdminUsers,
  getUserStatistics,
  getAdminUser,
  updateAdminUser,
  deleteAdminUser,
  banUser,
  unbanUser,
  suspendUser,
  activateUser,
  changeUserRole,
  setUserLimits,
  setUserAbuseScore,
  getUserStatusColor,
  getUserRoleColor,
  formatUserName,
  getUserInitials,
  formatLastLogin,
  // Admin Wallet types & functions
  type AdminWallet,
  type AdminWalletDetail,
  type WalletStatistics,
  type AdminWalletsResponse,
  type AdminWalletQueryParams,
  type AdminCreditRequest,
  type AdminDebitRequest,
  type AdminAdjustRequest,
  type AdminLockWalletRequest,
  getAdminWallets,
  getWalletStatistics,
  getAdminWallet,
  creditWallet,
  debitWallet,
  adjustWallet,
  lockWallet,
  unlockWallet,
  // Admin Analytics types & functions
  type DashboardOverview,
  type RevenueChartData,
  type UserGrowthChartData,
  type PaymentBreakdown,
  type MembershipBreakdown,
  type AuditLog,
  type SystemLog,
  type ChartQueryParams,
  type TopCountry,
  type TopService,
  getDashboardOverview,
  getRevenueChart,
  getUserGrowthChart,
  getPaymentBreakdown,
  getMembershipBreakdown,
  getRecentAuditLogs,
  getRecentSystemLogs,
  getTopCountries,
  getTopServices,
  type TrendResponse,
  type TrendDataPoint,
  getRevenueTrends,
  getActivationTrends,
  type RecentActivity,
  getRecentActivity,
  formatCurrency,
  formatNumber,
  getGrowthIndicator,
  getSystemHealthColor,
  getLogLevelColor,
  // Admin Membership types & functions
  type AdminSubscription,
  type MembershipStatistics,
  type AdminSubscriptionsResponse,
  type AdminSubscriptionQueryParams,
  type AdminGrantSubscriptionRequest,
  getAdminSubscriptions,
  getMembershipStatistics,
  grantSubscription,
  getSubscriptionStatusColor,
  // Admin API Keys types & functions
  type AdminApiKey,
  type ApiKeyStatistics,
  type AdminApiKeysResponse,
  type AdminApiKeyQueryParams,
  getAdminApiKeys,
  getApiKeyStatistics,
  adminRevokeApiKey,
  // Admin Payments types & functions
  type AdminPayment,
  type AdminPaymentDetail,
  type PaymentStatistics,
  type AdminPaymentsResponse,
  type AdminPaymentQueryParams,
  type AdminRefundRequest,
  type AdminMarkCompletedRequest,
  getAdminPayments,
  getPaymentStatistics,
  getAdminPayment,
  refundPayment,
  markPaymentCompleted,
  getGatewayInfo,
  formatPaymentAmount,
  formatPaymentDate,
  formatRelativeTime,
  // Admin Abuse Control types & functions
  type BlockType,
  type BlockedEntity,
  type AbuseConfig,
  type AbuseStatistics,
  type AtRiskUser,
  type UserAbuseInfo,
  type AbuseScoreHistory,
  type BlockedEntitiesResponse,
  type AtRiskUsersResponse,
  type BlockQueryParams,
  type AbuseUserQueryParams,
  type CreateBlockRequest,
  type AdjustScoreRequest,
  getAbuseConfig,
  getAbuseStatistics,
  getBlockedEntities,
  createBlock,
  removeBlock,
  getAtRiskUsers,
  getUserAbuseInfo,
  adjustUserAbuseScore,
  getUserAbuseHistory,
  getRiskLevelColor,
  getAbuseScoreColor,
  getBlockTypeColor,
} from './adminApi';

// smsApi re-declares CancelResponse and formatPrice from membershipApi, so exclude duplicates
export {
  type SmsOrderStatus,
  type SmsRentalStatus,
  type SmsProvider,
  type SmsService,
  type SmsCountry,
  type SmsProduct,
  type SmsOrder,
  type SmsRental,
  type SmsFavorite,
  type VipNumber,
  type SmsStatistics,
  type ProductQueryParams,
  type ServiceQueryParams,
  type CountryQueryParams,
  type OrderQueryParams,
  type RentalQueryParams,
  type AdminOrderQueryParams,
  type AdminRentalQueryParams,
  type AdminServiceQueryParams,
  type AdminCountryQueryParams,
  type PaginationParams,
  type PaginatedResponse,
  type ProvidersResponse,
  type ActivateResponse,
  type RentResponse,
  type SyncResponse,
  getProviders,
  getServices,
  getCountries,
  getProducts,
  getProductsRealtime,
  activateNumber,
  checkOrderStatus,
  cancelOrder,
  getOrderHistory,
  rentNumber,
  checkRentalStatus,
  cancelRental,
  getRentalHistory,
  getFavorites,
  addFavorite,
  removeFavorite,
  adminGetProviders,
  adminUpdateProvider,
  adminSyncProvider,
  adminGetServices,
  adminUpdateService,
  adminBulkDisableServices,
  adminGetCountries,
  adminUpdateCountry,
  adminGetOrders,
  adminGetOrder,
  adminRefundOrder,
  adminGetRentals,
  adminGetStatistics,
  adminGetVipNumbers,
  adminAddVipNumber,
  adminRemoveVipNumber,
  adminAutoDetectVip,
  getOrderStatusLabel,
  getOrderStatusColor,
  getRentalStatusLabel,
  getRentalStatusColor,
  getCountryFlag,
  getProviderBadge,
  canCancelOrder,
  canCancelRental,
  getTimeRemaining,
  formatDuration,
  SERVICE_CATEGORIES,
  RENTAL_DURATIONS,
} from './smsApi';

// SEO API
export * from './seoApi';

// Settings API - import directly to avoid duplicates
// export * from './settingsApi';

// Admin Modules API - import directly to avoid duplicates
// export * from './adminModulesApi';

// Teammate's APIs - import directly to avoid duplicates
// export * from './couponsApi';
export * from './adminReferralsApi';
export * from './ranksApi';
export * from './adminTicketsApi';
export * from './adminContactApi';
